/**
 * PDF Export Utility — uses browser print API
 * Creates a styled printable page from any content
 */

export function printElement(content: string, title: string, isRTL = true): void {
    const win = window.open('', '_blank', 'width=900,height=700');
    if (!win) return;

    win.document.write(`<!DOCTYPE html>
<html dir="${isRTL ? 'rtl' : 'ltr'}" lang="${isRTL ? 'ar' : 'en'}">
<head>
  <meta charset="UTF-8" />
  <title>${title}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Tajawal:wght@400;500;700&display=swap');
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Tajawal', Arial, sans-serif; font-size: 13px; color: #1a1a2e; background: #fff; direction: ${isRTL ? 'rtl' : 'ltr'}; }
    .page { max-width: 900px; margin: 0 auto; padding: 32px; }
    h1 { font-size: 20px; font-weight: 700; color: #1a1a2e; margin-bottom: 4px; }
    .subtitle { font-size: 12px; color: #64748b; margin-bottom: 24px; }
    table { width: 100%; border-collapse: collapse; margin-top: 16px; margin-bottom: 8px; }
    th { background: #f1f5f9; padding: 10px 12px; text-align: ${isRTL ? 'right' : 'left'}; font-size: 11px; font-weight: 700; color: #475569; text-transform: uppercase; border: 1px solid #e2e8f0; }
    td { padding: 10px 12px; border: 1px solid #e2e8f0; font-size: 12px; color: #334155; }
    tr:nth-child(even) td { background: #f8fafc; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: 11px; font-weight: 600; }
    .header-bar { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; padding-bottom: 16px; border-bottom: 2px solid #6366f1; }
    .logo { font-size: 22px; font-weight: 900; color: #6366f1; }
    .summary-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin: 20px 0; }
    .summary-card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 10px; padding: 14px 16px; text-align: center; }
    .summary-card .value { font-size: 20px; font-weight: 800; color: #6366f1; }
    .summary-card .label { font-size: 11px; color: #64748b; margin-top: 4px; }
    .detailed-row { background: #fff !important; border-bottom: 2px solid #6366f1 !important; }
    .item-table { font-size: 10px !important; margin-top: 4px !important; margin-bottom: 16px !important; background: #fcfcfd; }
    .item-table th { background: #fff; color: #64748b; padding: 6px 12px; border: 0; border-bottom: 1px solid #e2e8f0; }
    .item-table td { padding: 6px 12px; border: 0; border-bottom: 1px solid #f1f5f9; color: #64748b; }
    footer { margin-top: 32px; text-align: center; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 16px; }
    @media print { body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
  </style>
</head>
<body>
  <div class="page">
    ${content}
    <footer>
      ${isRTL ? 'تم الإنشاء بواسطة نظام المحاسبة السحابي' : 'Generated by SaaS Accounting System'} — ${new Date().toLocaleDateString(isRTL ? 'ar-SA' : 'en-US')}
    </footer>
  </div>
  <script>window.onload = () => { window.print(); }<\/script>
</body>
</html>`);

    win.document.close();
}

export function exportDetailedReportToPDF(
    title: string,
    subtitle: string,
    mainHeaders: string[],
    data: any[],
    mapMainRow: (item: any) => (string | number)[],
    mapItems: (item: any) => { headers: string[], rows: (string | number)[][] },
    summaryCards?: { label: string; value: string }[],
    isRTL = true
): void {
    const summaryHTML = summaryCards
        ? `<div class="summary-grid">${summaryCards.map(c => `<div class="summary-card"><div class="value">${c.value}</div><div class="label">${c.label}</div></div>`).join('')}</div>`
        : '';

    let contentHTML = ``;
    
    data.forEach((item) => {
        const mainRow = mapMainRow(item);
        const itemData = mapItems(item);
        
        contentHTML += `
        <div style="margin-bottom: 30px; page-break-inside: avoid;">
            <table style="margin-bottom: 0;">
                <thead><tr>${mainHeaders.map(h => `<th>${h}</th>`).join('')}</tr></thead>
                <tbody><tr class="detailed-row">${mainRow.map(cell => `<td style="font-weight: bold; color: #1e293b;">${cell}</td>`).join('')}</tr></tbody>
            </table>
            <table class="item-table" style="width: 95%; margin-${isRTL ? 'right' : 'left'}: auto;">
                <thead><tr>${itemData.headers.map(h => `<th>${h}</th>`).join('')}</tr></thead>
                <tbody>${itemData.rows.map(row => `<tr>${row.map(cell => `<td>${cell}</td>`).join('')}</tr>`).join('')}</tbody>
            </table>
        </div>`;
    });

    const signatureHTML = isRTL 
        ? `<div style="margin-top: 60px; display: flex; justify-content: space-between;">
             <div style="text-align: center; width: 200px; border-top: 1px solid #6366f1; padding-top: 8px;">توقيع المحاسب</div>
             <div style="text-align: center; width: 200px; border-top: 1px solid #6366f1; padding-top: 8px;">توقيع المدير العام</div>
           </div>`
        : `<div style="margin-top: 60px; display: flex; justify-content: space-between;">
             <div style="text-align: center; width: 200px; border-top: 1px solid #6366f1; padding-top: 8px;">Accountant Signature</div>
             <div style="text-align: center; width: 200px; border-top: 1px solid #6366f1; padding-top: 8px;">Manager Signature</div>
           </div>`;

    const fullHTML = `
    <div class="header-bar">
      <div class="logo">${isRTL ? 'نظام المحاسبة السحابي' : 'SaaS Accounting System'}</div>
      <div style="text-align:${isRTL ? 'left' : 'right'}; font-size:12px; color:#64748b;">
        ${new Date().toLocaleDateString(isRTL ? 'ar-SA' : 'en-US')}
      </div>
    </div>
    <h1>${title}</h1>
    <p class="subtitle">${subtitle}</p>
    ${summaryHTML}
    ${contentHTML}
    ${signatureHTML}`;

    printElement(fullHTML, title, isRTL);
}

export function exportTableToPDF(
    title: string,
    subtitle: string,
    headers: string[],
    rows: (string | number)[][],
    summaryCards?: { label: string; value: string }[],
    isRTL = true
): void {
    const summaryHTML = summaryCards
        ? `<div class="summary-grid">${summaryCards.map(c => `<div class="summary-card"><div class="value">${c.value}</div><div class="label">${c.label}</div></div>`).join('')}</div>`
        : '';

    const tableHTML = `
    <table>
      <thead><tr>${headers.map(h => `<th>${h}</th>`).join('')}</tr></thead>
      <tbody>${rows.map(row => `<tr>${row.map(cell => `<td>${cell}</td>`).join('')}</tr>`).join('')}</tbody>
    </table>`;

    const signatureHTML = isRTL 
        ? `<div style="margin-top: 60px; display: flex; justify-content: space-between;">
             <div style="text-align: center; width: 200px; border-top: 1px solid #6366f1; padding-top: 8px;">توقيع المحاسب</div>
             <div style="text-align: center; width: 200px; border-top: 1px solid #6366f1; padding-top: 8px;">توقيع المدير العام</div>
           </div>`
        : `<div style="margin-top: 60px; display: flex; justify-content: space-between;">
             <div style="text-align: center; width: 200px; border-top: 1px solid #6366f1; padding-top: 8px;">Accountant Signature</div>
             <div style="text-align: center; width: 200px; border-top: 1px solid #6366f1; padding-top: 8px;">Manager Signature</div>
           </div>`;

    const content = `
    <div class="header-bar">
      <div class="logo">${isRTL ? 'نظام المحاسبة السحابي' : 'SaaS Accounting System'}</div>
      <div style="text-align:${isRTL ? 'left' : 'right'}; font-size:12px; color:#64748b;">
        ${new Date().toLocaleDateString(isRTL ? 'ar-SA' : 'en-US')}
      </div>
    </div>
    <h1>${title}</h1>
    <p class="subtitle">${subtitle}</p>
    ${summaryHTML}
    ${tableHTML}
    ${signatureHTML}`;

    printElement(content, title, isRTL);
}

export function formatSAR(amount: number): string {
    return new Intl.NumberFormat('ar-SA', { style: 'currency', currency: 'SAR', minimumFractionDigits: 0 }).format(amount);
}
